FROM ashishsharma0012/asterisk:3
MAINTAINER Ashish Sharma

RUN chown asterisk:asterisk /var/run/asterisk
RUN chown -R asterisk:asterisk /etc/asterisk/
RUN chown -R asterisk:asterisk /var/{lib,log,spool}/asterisk
RUN chown -R asterisk:asterisk /usr/lib64/asterisk/

RUN pip install supervisor 
RUN echo_supervisord_conf > /etc/supervisord.conf
ADD ./supervisord_add_conf /tmp/supervisord_add_conf
RUN cat /tmp/supervisord_add_conf >> /etc/supervisord.conf
RUN rm /tmp/supervisord_add_conf
EXPOSE 5060/udp
EXPOSE 5060/tcp
EXPOSE 5061/udp
EXPOSE 5061/tcp
EXPOSE 10000-10099/udp		

CMD ["supervisord", "-c", "/etc/supervisord.conf"]	
